# Site settings
title: "David Dawson"
email: me@daviddawson.me
description: > # Microservices made easy
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: davidthecoder
github_username:  daviddawson
url: http://daviddawson.me

# Build settings
markdown: kramdown

paginate: 4
#paginate_path: "blog/page:num"

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-asciidoc
  - asciidoctor-diagram

category-list: [learning, microservices-react, publications]

asciidoc_ext: asciidoc,adoc,ad

asciidoctor:
  attributes:
    - hardbreaks!
    - icons=font
  # - source-highlighter=coderay
    - source-highlighter=pygments
    - pygments-css=style
    - coderay-css=style
#    - imagesdir=/images
    - stylesdir=css
    - env-doc
