---
layout: documentation
---
:title: David Dawson
:date: 2015-01-05 11:40
:comments: true
:sharing: true
:source-highlighter: pygments
:toc: right
:toc-title: Services
:toclevels: 6

## I'm available for hire!

I operate as a freelancer out of the UK. I do significant work in Europe and occasional work in the US, Africa
and the Middle East.  I do approximately half of my work remotely, and look well on any engagements that offer this
as an option.

If you want to start on a Microservice journey, health check a cloud deployment, design a resilient data architecture or need an experienced systems architect
and team lead, get in touch.

I use three commercial models, Simple T&M, Fixed Price delivery and Monthly Retainer. See below for details on how to engage me.

Here are some of the services I can provide.

### Microservices and Cloud Computing

I work extensively in cloud environments, following my work over the past 5 years in Microservices and related domains.

#### Microservices

I have worked on Microservices projects of many kinds for years, as a developer, consultant, systems architect and
devops team lead.

I have seen all aspects of the lifecycle, from bootstrap, team scaling, development process, production issues ...

I founded the link:http://muoncore.io[Muon Project] to solve some of th recurring issues that I've seen around
inter service communication, data, consistency and resilience.

If you are starting on Microservices, or are well on your journey, I can help you.

See link:/training/microservices.html[my 3 day Microservices adoption workshop]

#### Cloud Foundry

I have worked with Pivotal for many years on consultancy and training for their distribution of Cloud Foundry -
PCF.

I deliver much of the training across EMEA for Pivotal on their PCF product set.

If you have a need to deploy, manage, extend or gain more knowledge about Cloud Foundry in general and PCF in particular,
get in touch with your requirements. I can work with you on delivering training (Pivotal approved), consultancy and longer term
projects.

### Groovy and Groovy technologies

Groovy is a rich, optionally typed language on the JVM.
I can get you started using Groovy and provide long term help
adopting Groovy in your organisation.

See link:/training/groovy.html[my 3 day Groovy training course]

### IoT End to End System Design and Delivery

I work with an electronics manufacturer to deliver Internet of Things solutions that I design, have manufactured  and coordinate back end development
and delivery for.

Using the Muon project that I founded, I have developed large scale analytic applications and associated hardware sensors
for varying fields including _passive house monitoring_ and industrial monitoring_.

These use a combination of LoRa wide area communications (up to 10 mile rangeon AA batteries), ZigBee for shorter range and
a custom gateway hardware for backhaul to the Muon based back end.

If you have a need for deploying sensors distributed across a large area and processing the data analytically, get in touch.

## Engagement Styles

I am available as a freelancer only, not as a permanent employee or full time contractor.

### T&M

You want work doing, we agree an hourly or daily rate and I do it for you. I expect a simple interview process, no multi
week processes please.

I am not available full time, but I can give you booked out weeks and days in a month to give consistency, just not all of them.

### Fixed Price Delivery

You have a project that needs completing, I scope it and give you a fixed price to deliver.

If I need more resources, I will engage contractors, freelancers and agencies to help deliver and maintain it.

This engagement is best if you have a discrete, well defined piece of work that you don't have the resources to deliver
and would like to engage me long term to build and look after it.

Once it's built, we'll move to a monthly retainer for ongoing work.

### Monthly Retainer

In this model, you buy a certain number of hours per month, at a reduced rate compared to simple T&M. You agree a contract 6-12 months
in advance that is then fixed.

If you need more hours in a month, the T&M rate will apply.

This engagement works best if you have an existing system that I have either built, designed or consulted on that
you need ongoing maintenance, advice and consultancy in the long term.
